[project]
name = "jtrm-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "jtrm",
]

[tool.uv.sources]
jtrm = { path = "../jtrm-core", editable = true }
